image: node:18

stages:
  - build
  - deploy

variables:
  NODE_ENV: development
  RAILWAY_TOKEN: $RAILWAY_TOKEN  # Set this in GitLab CI/CD variables



deployBackend:
  stage: deploy
  script:
    - cd backend/
    - npm install
    - ./node_modules/.bin/railway up --service chat_node_backend --detach
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes: 
        - backend/**/*

# deployBackend:
#   stage: deploy
#   script:
#     - npm exec railway up # Deploy using Railway CLI
#   rules:
#     - if: $CI_COMMIT_BRANCH == "master"
#       changes: 
#         - backend/**/*
